export const experiences = [
  { slug:"do-pulse", name:"DO PULSE", type:"Dance Fitness", level:"All levels", duration:"50 minutes", pillar:"Movement", intro:"A high-energy class that blends dance and aerobic movement to build stamina, coordination and rhythm.", focus:["Stamina","Coordination","Flexibility"], image:"https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?auto=format&fit=crop&w=1800&q=88", cue:"Rhythm becomes momentum", accent:"#b86138", session:["Arrive in the rhythm","Build the sequence","Finish on a high"] },
  { slug:"do-flow", name:"DO FLOW", type:"Yoga", level:"All levels", duration:"50 minutes", pillar:"Mindfulness", intro:"Mindful movement and breath that support flexibility, posture, body awareness and inner calm.", focus:["Flexibility","Balance","Calm"], image:"https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&w=1800&q=88", cue:"Space to breathe deeper", accent:"#7d876f", session:["Settle through breath","Move with intention","Rest and integrate"] },
  { slug:"do-transform", name:"DO TRANSFORM", type:"Functional Training", level:"Beginner & moderate", duration:"50 minutes", pillar:"Strength", intro:"Strength, mobility and endurance-based movement that helps the body perform better in everyday life.", focus:["Mobility","Endurance","Coordination"], image:"https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=1800&q=88", cue:"Ready for real life", accent:"#596d63", session:["Prime the body","Train complete patterns","Reset and recover"] },
  { slug:"do-build", name:"DO BUILD", type:"Strength Training", level:"All levels", duration:"50 minutes", pillar:"Strength", intro:"Guided strength training designed to build muscle strength, improve posture and grow body confidence.", focus:["Strength","Technique","Posture"], image:"https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=1800&q=88", cue:"Strong is a practice", accent:"#76566d", session:["Prepare with purpose","Build progressive strength","Leave feeling capable"] },
  { slug:"do-grow", name:"DO GROW", type:"Kids Strength Training", level:"Beginner & intermediate", duration:"50 minutes", pillar:"Strength", intro:"Safe, age-appropriate movement for strength, balance, coordination and confidence.", focus:["Balance","Movement","Confidence"], image:"https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?auto=format&fit=crop&w=1800&q=88", cue:"Confidence starts in motion", accent:"#a88872", session:["Play and prepare","Learn strong movement","Celebrate progress"] },
  { slug:"do-fly", name:"DO FLY", type:"Aerial Yoga", level:"All levels", duration:"50 minutes", pillar:"Mindfulness", intro:"Yoga with the support of a suspended hammock for flexibility, balance, body control and deeper stretching.", focus:["Flexibility","Circulation","Relaxation"], image:"https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=1800&q=88", cue:"A new point of balance", accent:"#986044", session:["Meet the hammock","Explore supported shapes","Return gently to ground"] },
  { slug:"do-reset", name:"DO RESET", type:"Recovery", level:"All levels", duration:"50 minutes", pillar:"Recovery", intro:"A calm recovery ritual bringing together sauna, cold plunge and red light therapy.", focus:["Recovery","Circulation","Relaxation"], image:"https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=1800&q=88", cue:"Pause with a purpose", accent:"#5f716c", session:["Warm and release","Meet the cold","Rest in light"] },
  { slug:"do-complete", name:"DO COMPLETE", type:"Unlimited Sessions", level:"Integrated wellness", duration:"Flexible", pillar:"Complete", intro:"An integrated membership path through strength, mindful movement and recovery.", focus:["Movement","Mindfulness","Recovery"], image:"https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?auto=format&fit=crop&w=1800&q=88", cue:"Your whole week, connected", accent:"#964e2c", session:["Choose your movement","Balance your week","Recover with intention"] },
] as const;
