export const experiences = [
  {
    slug: "do-pulse", name: "DO PULSE", type: "Dance Fitness", level: "All levels", duration: "50 minutes", pillar: "Movement",
    intro: "Dance movement meets aerobic exercise in a class built around rhythm, stamina and coordination.",
    focus: ["Stamina", "Coordination", "Flexibility"],
    image: "/do-pulse-editorial.webp",
    cue: "Find your energy in the rhythm", accent: "#b86138",
    session: ["Find the beat", "Build the movement", "Finish with energy"],
    forYou: "For days when you want movement to feel expressive and energising.",
    firstVisit: "Wear comfortable clothes you can move freely in. Let the coach know it is your first dance fitness class.",
    pairWith: "do-flow",
  },
  {
    slug: "do-flow", name: "DO FLOW", type: "Yoga", level: "All levels", duration: "50 minutes", pillar: "Mindfulness",
    intro: "Movement and breath come together to explore balance, flexibility, posture and body awareness.",
    focus: ["Flexibility", "Balance", "Calm"],
    image: "/pillar-mindfulness.webp",
    cue: "Make room for breath", accent: "#727d71",
    session: ["Arrive through breath", "Move with attention", "Take a moment to settle"],
    forYou: "For a slower practice that still gives your body room to move.",
    firstVisit: "Come in comfortable clothing and tell the coach about your experience with yoga so they can suggest options.",
    pairWith: "do-build",
  },
  {
    slug: "do-transform", name: "DO TRANSFORM", type: "Functional Training", level: "Beginner & moderate", duration: "50 minutes", pillar: "Strength",
    intro: "Functional movement brings strength, mobility, balance and endurance into the same practice.",
    focus: ["Mobility", "Endurance", "Coordination"],
    image: "/pillar-strength.webp",
    cue: "Movement for real life", accent: "#596d63",
    session: ["Prepare the body", "Connect movement patterns", "Slow down and reset"],
    forYou: "For anyone who wants training that carries into everyday movement.",
    firstVisit: "Share your current training experience and any movement concerns before the session begins.",
    pairWith: "do-flow",
  },
  {
    slug: "do-build", name: "DO BUILD", type: "Strength Training", level: "All levels", duration: "50 minutes", pillar: "Strength",
    intro: "Guided strength training with attention to technique, posture and growing confidence.",
    focus: ["Strength", "Technique", "Posture"],
    image: "/pillar-strength.webp",
    cue: "Strength is a practice", accent: "#76566d",
    session: ["Learn the movement", "Build with guidance", "Leave feeling capable"],
    forYou: "For building strength with clear instruction at your own level.",
    firstVisit: "You do not need to know the equipment in advance. Tell your coach where you are starting from.",
    pairWith: "do-reset",
  },
  {
    slug: "do-grow", name: "DO GROW", type: "Kids Strength Training", level: "Beginner & intermediate", duration: "50 minutes", pillar: "Strength",
    intro: "Age-appropriate movement explores strength, balance, coordination and confidence.",
    focus: ["Balance", "Movement", "Confidence"],
    image: "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?auto=format&fit=crop&w=1800&q=88",
    cue: "Confidence starts in motion", accent: "#a88872",
    session: ["Get comfortable moving", "Explore guided movement", "Celebrate what was learned"],
    forYou: "For parents looking for a guided introduction to movement for their child.",
    firstVisit: "Ask the studio to confirm current age suitability and supervision details before your child attends.",
    pairWith: "do-flow",
  },
  {
    slug: "do-fly", name: "DO FLY", type: "Aerial Yoga", level: "All levels", duration: "50 minutes", pillar: "Mindfulness",
    intro: "Yoga with a suspended hammock invites balance, supported stretching and new ways to move.",
    focus: ["Flexibility", "Balance", "Body control"],
    image: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=1800&q=88",
    cue: "See movement differently", accent: "#986044",
    session: ["Meet the hammock", "Explore supported shapes", "Return gently to the ground"],
    forYou: "For curiosity about movement, support and a different point of balance.",
    firstVisit: "Tell the studio it is your first aerial class and ask about clothing and any preparation before attending.",
    pairWith: "do-build",
  },
  {
    slug: "do-reset", name: "DO RESET", type: "Recovery", level: "Ask the studio", duration: "Confirm with studio", pillar: "Recovery",
    intro: "A considered recovery ritual with sauna, cold plunge and red-light experiences.",
    focus: ["Heat", "Cold", "Light"],
    image: "/pillar-recovery.webp",
    cue: "Give recovery its own time", accent: "#5f716c",
    session: ["Explore warmth", "Consider cold immersion", "Pause in light"],
    forYou: "For making recovery a deliberate part of your routine.",
    firstVisit: "Ask the team for current session details, preparation and suitability guidance. Consult a qualified professional if you have a health concern.",
    pairWith: "do-build",
  },
  {
    slug: "do-complete", name: "DO COMPLETE", type: "Integrated Membership", level: "Membership", duration: "Flexible", pillar: "Complete",
    intro: "A way to bring movement, strength, mindfulness and recovery into one connected routine.",
    focus: ["Movement", "Mindfulness", "Recovery"],
    image: "/story-interior-editorial.webp",
    cue: "Make the whole week yours", accent: "#964e2c",
    session: ["Choose your movement", "Balance your week", "Make room to recover"],
    forYou: "For exploring Do Well as a complete, ongoing practice.",
    firstVisit: "Speak with the studio about current membership access, inclusions and pricing before choosing a plan.",
    pairWith: "do-flow",
  },
] as const;

export function experienceHref(slug: (typeof experiences)[number]["slug"]) {
  if (slug === "do-reset") return "/recovery";
  if (slug === "do-complete") return "/membership";
  return `/classes/${slug}`;
}
